### ISSUE TITLE
高品质音乐403

### ISSUE THREAD

**Issue by jsososo** [mzz2017/musicman#22]
腾讯好像昨天开始修改了高品质音乐对策略，很多音乐的非128k都无法再通过之前的方式获取了，一直是403，现在有一点无从下手

**Comment by jsososo** [comment]
找到问题了，域名改过了，从 y.qq.music 来看新的域名 http://183.131.60.16/amobile.music.tc.qq.com/ 亲测可用

**Comment by mzz2017** [comment]
感谢您的贡献，demo站将稍后恢复。
